services:

    nginx:
        build:
            context: gears/nginx/.
            dockerfile: Dockerfile
        container_name: nginx
        image: nginx_t:0.0.1 
        restart: on-failure
        network_mode: "service:tailscale" 
        depends_on:
            - backend
            - frontend

    backend:
        build: 
            context : gears/backend/.
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - ./gears/backend:/data
            - /data/node_modules
        environment:
            - APP_MODE=${APP_MODE}
            - DATABASE_URL=postgresql://user_admin:mon_password_secret@db:5432/db
        image:  backend
        networks:
            - Solar_Cam
        expose:
            - "3000"
        ports:
            - "5555:5555"
        depends_on:
            - db
            - frontend
        restart: on-failure

    frontend:
        build: 
            context : gears/frontend/.
            dockerfile: Dockerfile
        container_name: frontend
        volumes:
            - ./gears/frontend/src:/data 
            - /data/node_modules
        environment:
            - APP_MODE=${APP_MODE}
        image:  frontend
        networks:
            - Solar_Cam
        expose:
            - "5173"
        restart: on-failure

    db:
        build:
            context : gears/db/.
            dockerfile : Dockerfile
        container_name : db 
        volumes:
            - ./gears/db/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=user_admin
            - POSTGRES_PASSWORD=mon_password_secret
            - POSTGRES_DB=db
        networks:
            - Solar_Cam
        ports:
            - "5432:5432"
        restart: always

    tailscale:
        image: tailscale/tailscale:latest
        container_name: tailscale
        hostname: Solar-Cams
        env_file: gears/tailscale/.env
        volumes:
            - ./gears/tailscale/tailscale_data:/var/lib/tailscale
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        networks:
            - Solar_Cam
        restart: unless-stopped
        
    
    go2rtc:
        image: alexxit/go2rtc
        container_name: go2rtc
        network_mode: "service:tailscale"
        env_file:
            - gears/go2rtc/.env
        volumes:
            - ./gears/go2rtc/go2rtc.yaml:/config/go2rtc.yaml
        restart: always
    

networks:
    Solar_Cam:
        driver: bridge